# the viewer
pipeline:
  - __target__: camkit.ops.network.subscriber
    publish_url: {{ publish_url }}
  - __target__: camkit.ops.imaging.fit_width
    width: {{ width | default(1920) }}
    height: {{ height | default(1080) }}
    preserve_aspect: {{ preserve_aspect |  default(true) }}
  - __target__: camkit.ops.viewer.viewer_cv2
    fullscreen: {{ fullscreen | default(false) }}
  - __target__: camkit.ops.utils.stats

