# the camera
camera:
  __target__: camkit.camera.Camera
  camera_id: {{ camera_id | default(0) }}
  mode: {{ camera_mode | default(1) }}
  vflip: false
  hflip: false
  preview: false


# configure the camera
configure_cam:
  - __target__: camkit.camera.set_whitebalance
    camera:
      __instance__: camera
  - __target__: camkit.camera.set_exposure
    camera:
      __instance__: camera
    wait: true
  - __target__: camkit.camera.set_focus
    camera:
      __instance__: camera
    wait: true
  - __target__: camkit.utils.save_camera_configs
    camera:
      __instance__: camera
    outdir: {{ output_dir }}


# the pipeline of generators
pipeline:
  - __target__: camkit.ops.control.flirc
  - __target__: camkit.ops.camera.capture
    camera:
      __instance__: camera
    arrays:
      - main
  # - __target__: camkit.ops.debug.dump
  - __target__: camkit.ops.sink.save_item
    outdir: {{ output_dir }}
  - __target__: camkit.ops.sink.save_rgb
    outdir: {{ output_dir }}

