# the camera
camera:
  __target__: camkit.camera.Camera
  camera_id: {{ camera_id | default(0) }}
  mode: {{ camera_mode | default(5) }}
  max_fps: {{ 4.0 * (fps | default(0.5) | float) }}
  preview: false
  vflip: {{ vflip | default(false) }}
  hflip: {{ hflip | default(false) }}
  tuning_file: {{ tuning_file | default('imx219_noir.json') }}


configure_cam:
  - __target__: camkit.camera.set_whitebalance
    camera:
      __instance__: camera
    mode:
      __enum__: camkit.camera.AwbModeEnum.AUTO
  - __target__: camkit.camera.set_exposure
    camera:
      __instance__: camera
    metering_mode:
      __enum__: camkit.camera.MeteringModeEnum.MATRIX
    exposure_mode:
      __enum__: camkit.camera.ExposureModeEnum.LONG
    constraint_mode:
      __enum__: camkit.camera.ConstraintModeEnum.SHADOWS
    wait: true
  - __target__: camkit.utils.save_camera_configs
    camera:
      __instance__: camera
    outdir: {{ output_dir }}


# the pipeline of generators
pipeline:
  - __target__: camkit.ops.control.simple
    fps: {{ fps | default(0.5) }}
  - __target__: camkit.ops.camera.capture
    camera:
      __instance__: camera
    arrays:
      - main
  - __target__: camkit.ops.sink.save_item
    outdir: {{ output_dir }}
  - __target__: camkit.ops.sink.save_rgb
    outdir: {{ output_dir }}

