# the camera
camera:
  __target__: camkit.camera.Camera
  camera_id: {{ camera_id | default(0) }}
  mode: {{ camera_mode | default(1) }}
  vflip: false
  hflip: false
  preview: false


# configure the camera
configure_cam:
  - __target__: camkit.camera.set_whitebalance
    camera:
      __instance__: camera
  - __target__: camkit.camera.set_exposure
    camera:
      __instance__: camera
    wait: true
  - __target__: camkit.camera.set_focus
    camera:
      __instance__: camera
    mode:
      __enum__: camkit.camera.AfModeEnum.CONTINUOUS
    not_available_ok: true
    wait: true
  - __target__: camkit.utils.save_camera_configs
    camera:
      __instance__: camera
    outdir: {{ output_dir }}


# the pipeline of generators
pipeline:
  - __target__: camkit.ops.control.simple
    fps: {{ 1.0 / (timelapse_seconds | default(60) | int) }}
    max_frames: {{ max_frames | default(10) }}
  - __target__: camkit.ops.camera.capture
    camera:
      __instance__: camera
    arrays:
      - main
  # - __target__: camkit.ops.sink.save_item
  #   outdir: {{ output_dir }}
  - __target__: camkit.ops.sink.save_movie
    movie_fps: 5
    images_per_movie: {{ images_per_movie | default(100) }}
    outdir: {{ output_dir }}

