from typing import Iterable, Generator
import time


def warmup(
    pipe: Iterable[dict], 
    *, 
    frames: int = 0, 
    seconds: float = 0
) -> Generator[dict, None, None]:
    """Discard the initial frames generated by the pipeline to give the cameras time to settle.

    Items are discarded until both the frame count and time exceed the passed in parameters.
    """

    print("Building camkit.ops.utils.warmup")
    if frames > 0:
        print(f"- frames: {frames}")
    if seconds > 0:
        print(f"- seconds: {seconds}")

    def gen():
        print("Warmup running")
        warm = False
        start = time.monotonic()
        for idx, item in enumerate(pipe):
            runtime = time.monotonic() - start
            if idx < frames or runtime < seconds:
                continue
        
            if warm == False:
                print("Warmup finished")
                warm = True
        
            yield item

    return gen()
